var products = [
    {
        name: 'Samsung Galaxy S10',
        img: 'img/Samsung_S10.jpg',
        description: '',
        price: 68999,
        quantity: 0,
        id: false,
    },
    {
        name: 'Sony Xperia XZ3',
        img: 'img/Sony_XZ3.png',
        description: '',
        price: 59990,
        quantity: 0,
        id: false,
    },
    {
        name: 'Apple IPhone XR.jpg',
        img: 'img/Apple_IPhone_XR.jpg',
        description: '',
        price: 52990,
        quantity: 0,
        id: false,
    },
    {
        name: 'Huawei Mate 20 PRO',
        img: 'img/Huawei_Mate_20_PRO.jpg',
        description: '',
        price: 59990,
        quantity: 0,
        id: false,
    },
    {
        name: 'Caterpillar CAT S61',
        img: 'img/Caterpillar_CAT_S61.jpg',
        description: '',
        price: 59990,
        quantity: 0,
        id: false,
    },
    {
        name: 'Gresso Meridian M5',
        img: 'img/Gresso_Meridian_M5.png',
        description: '',
        price: 252000,
        quantity: 0,
        id: false,
    },
    {
        name: 'microSD Samsung 512Gb',
        img: 'img/microSD_Samsung_512Gb.jpg',
        description: '',
        price: 12999,
        quantity: 0,
        id: false,
    },
    {
        name: 'Xiaomi Mi Power 2',
        img: 'img/Xiaomi_Mi_Power_2.jpg',
        description: '',
        price: 1590,
        quantity: 0,
        id: false,
    },
    {
        name: 'Luxcase 3D iPhone XR',
        img: 'img/Luxcase_3D_iPhone_XR.jpg',
        description: '',
        price: 1999,
        quantity: 0,
        id: false,
    },
    {
        name: 'Gresso iPhone XR Гуайра',
        img: 'img/Gresso_iPhone_XR_Гуайра.jpg',
        description: '',
        price: 599,
        quantity: 0,
        id: false,
    },
    {
        name: 'Huawei Smart View',
        img: 'img/Huawei_Smart_View.jpg',
        description: '',
        price: 1799,
        quantity: 0,
        id: false,
    },
    {
        name: 'Luxcase 3D Huawei Mate',
        img: 'img/Luxcase_3D_Huawei_Mate.jpg',
        description: '',
        price: 1499,
        quantity: 0,
        id: false,
    }
];